services:
  db:
    image: postgres:15
    env_file:
      - ./.envs/.env.postgres
    ports:
      - 5440:5432
    networks:
      - "local-development"
  tests:
    build:
      dockerfile: ./deployment/testing/Dockerfile
    env_file:
      - ./.envs/.env.base
      - ./.envs/.env.test
    ports:
      - 9001:9000
    networks:
      - "local-development"

  app:
    build:
      dockerfile: ./deployment/Dockerfile
    env_file:
      - ./.envs/.env.base
      - ./.envs/.env.dev
    ports:
      - 9001:9000
    networks:
      - "local-development"
networks:
  local-development: