# Generated by Django 5.0.4 on 2024-05-23 19:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField()),
            ],
        ),
    ]
